<section class="grid two">
  <article class="card">
    <div class="card-head"><h2>DOCX Generator</h2></div>
    <form method="post" action="<?= e(app_url('word/generate')) ?>" class="stack">
      <input type="hidden" name="_csrf" value="<?= e($csrf) ?>">
      <label>Title<input type="text" name="title" value="Automation Report" required></label>
      <label>Content<textarea name="content" rows="9" required>Generated by the secure PHP MVC Automation System.</textarea></label>
      <button class="btn primary" type="submit">Generate DOCX</button>
    </form>
  </article>
  <article class="card">
    <div class="card-head"><h2>Documents</h2></div>
    <div class="table-wrap">
      <table>
        <thead><tr><th>Title</th><th>Created</th><th>File</th></tr></thead>
        <tbody>
        <?php foreach ($files as $file): ?>
          <tr><td><?= e($file['title']) ?></td><td><?= e($file['created_at']) ?></td><td><a href="<?= e('../' . $file['file_path']) ?>" download>Download</a></td></tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </article>
</section>
